model_name: hoptimus0
type: timm
vlm: false
emb_dim: 1536
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/hoptimus0/pytorch_model.bin
hf_tag: hf-hub:bioptimus/H-optimus-0

timm_kwargs: 
  init_values: 1e-5
  dynamic_img_size: False
