model_name: hoptimus1
type: timm
vlm: false
emb_dim: 1536
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/hoptimus1/pytorch_model.bin
hf_tag: hf-hub:bioptimus/H-optimus-1

timm_kwargs: 
  init_values: 1e-5
  dynamic_img_size: False
