model_name: musk
type: timm
vlm: true
emb_dim: 2048
emb_dim_seg: 1024
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/musk/model.safetensors
hf_tag: hf-hub:xiangjx/musk

timm_kwargs: {}
