model_name: titan
type: safetensors
vlm: false # titan/conch1.5 is a VLM but 'false' as conch1.5 patch-level text encoder is has not yet been released publicly (see https://github.com/mahmoodlab/TITAN/issues/17).
emb_dim: 768
emb_dim_seg: 1024
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/titan
