model_name: uni
type: timm
vlm: false
emb_dim: 1024
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/uni/pytorch_model.bin
hf_tag: hf-hub:MahmoodLab/uni

timm_kwargs: 
  img_size: 224
  patch_size: 16
  init_values: 1e-5
  num_classes: 0
  dynamic_img_size: True
