model_name: uni2h
type: timm
vlm: false
emb_dim: 1536
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/uni2h/pytorch_model.bin
hf_tag: hf-hub:MahmoodLab/UNI2-h

timm_kwargs: 
  img_size: 224
  patch_size: 14
  depth: 24
  num_heads: 24
  init_values: 1e-5
  embed_dim: 1536
  mlp_ratio: 5.33334 #2.66667 * 2
  num_classes: 0
  no_embed_class: True
  mlp_layer: SwiGLUPacked
  act_layer: SiLU
  reg_tokens: 8
  dynamic_img_size: True
