model_name: virchow
type: timm
vlm: false
emb_dim: 2560
emb_dim_seg: 1280
ckpt_path: ${oc.env:THUNDER_BASE_DATA_FOLDER}/pretrained_ckpts/virchow/pytorch_model.bin
hf_tag: hf-hub:paige-ai/Virchow

timm_kwargs:
  mlp_layer: SwiGLUPacked
  act_layer: SiLU
