dataset_name: ocelot
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["pre_computing_embeddings", "segmentation"]
nb_train_samples: 6400
nb_val_samples: 2192
nb_test_samples: 2016
md5sum: "afe1ad1902e11a8f6814aebab6745ffb"
image_sizes: [[1024, 1024]]
mpp: 0.20
classes: ["Background", "Cancer Area"]
class_to_id:
  Background: 0
  Cancer Area: 1
id_to_class:
  0: Background 
  1: Cancer Area
