dataset_name: segpath_lymphocytes
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["pre_computing_embeddings", "segmentation"]
nb_train_samples: 94077 
nb_val_samples: 9738
nb_test_samples: 6642
md5sum: "ddd5283086bdd583ac644df81ae965a6"
image_sizes: [[984, 984]]
mpp: 0.22
classes: ["no-lymphocytes", "lymphocytes"]
class_to_id:
  no-lymphocytes: 0
  lymphocytes: 1
id_to_class:
  0: no-lymphocytes
  1: lymphocytes
