dataset_name: segpath_epithelial
nb_classes: 2
base_data_folder: ${oc.env:THUNDER_BASE_DATA_FOLDER}/datasets/
compatible_tasks: ["pre_computing_embeddings", "segmentation"]
nb_train_samples: 197208
nb_val_samples: 20331
nb_test_samples: 21042
md5sum: "8d28d9b91e5d37a8fc070a8cf8a708ef"
image_sizes: [[984, 984]]
mpp: 0.22
classes: ["no-epithelial", "epithelial"]
class_to_id:
  no-epithelial: 0
  epithelial: 1
id_to_class:
  0: no-epithelial
  1: epithelial
